[bugfix][v0.26.0]Fix weight loading for modelslim FAQuant model (#14540)
### What this PR does / why we need it?

Fix weight loading for some modelslim FAQuant model.
There are two issues about it.
- For `DeepSeek-V3.1-W8A8C8` which has a `FAQuant` MTP layer, there is
KeyError: 'model.layers.61.mtp_block.self_attn.fa_k.offset'. Because the
upstream vllm `DeepSeekMTP` not using the `AutoWeightLoader`, we patch
`DeepseekMTP` to fix it. Related main branch PR: #13684 , and for main
branch, this patch has already been deleted in #10896, and vllm-ascend
will keep the `deepseek_mtp` modeling file.
- For `Kimi-K2.6-W4A4C8` which has `FAQuant`, there is KeyError:
'layers.0.self_attn.mla_attn.mla_attn.mla_attn.mla_attn.fa_k.offset'
. `KimiK25ForConditionalGeneration.load_weights` will call
`AutoWeightsLoader` and the inner `language_model` (actually
`DeepseekV2ForCausalLM`) will also call `AutoWeightsLoader`, our suffix
mapper will run twice, and make a wrong key
`'layers.0.self_attn.mla_attn.mla_attn.mla_attn.mla_attn.fa_k.offset'`
instead of `'layers.0.self_attn.mla_attn.mla_attn.fa_k.offset'`. We use
a regex mapper to avoid this situation.



### Does this PR introduce _any_ user-facing change?

### How was this patch tested?

Test on  DeepSeek-V3.1-W8A8C8 and Kimi-K2.6-W4A4C8

- vLLM version: v0.26.0
- vLLM main:
https://github.com/vllm-project/vllm/commit/d02df748bf9efd99022f1a062597dc3cb3808485

Signed-off-by: menogrey <1299267905@qq.com>